apiVersion: v1
kind: Pod
metadata:
  name: pod-pvc
spec:
  containers:
  - name: app
    image: busybox
    command: ["/bin/sh", "-c", "echo Hello Persistent World > /data/hello.txt; sleep 3600"]
    volumeMounts:
    - name: my-storage
      mountPath: /data
  volumes:
  - name: my-storage
    persistentVolumeClaim:
      claimName: my-pvc
