apiVersion: v1
kind: Pod
metadata:
  name: logger-pod
spec:
  containers:
  - name: logger
    image: busybox
    command: ["/bin/sh"]
    args: ["-c", "while true; do echo $(date) - Hello from the logs!; sleep 1; done"]
